name: Neon Backup

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Create backup folder
        run: mkdir -p backups

      - name: Dump database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          pg_dump "$DATABASE_URL" > backups/backup.sql

      - name: Rename backup with timestamp
        run: |
          mv backups/backup.sql backups/backup-$(date +%Y-%m-%d-%H-%M).sql

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: neon-db-backup
          path: backups/
